services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1026 # Synology users often have different UIDs, check via SSH if needed
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - ./config/transmission:/config
      # Single unified download path for Synology
      - /volume1/downloads/complete:/downloads/complete
      - /volume1/downloads/incomplete:/downloads/incomplete
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - ./config/radarr:/config
      # Temporary destination where Radarr prepares movies before manual move
      - /volume1/media/movies:/movies
      # Must match Transmission exactly to grab downloaded files
      - /volume1/downloads/complete:/downloads/complete
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - ./config/sonarr:/config
      # Temporary destination where Sonarr prepares shows before manual move
      - /volume1/media/shows:/shows
      # Must match Transmission exactly to grab downloaded files
      - /volume1/downloads/complete:/downloads/complete
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - ./config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
    ports:
      - 8191:8191
    restart: unless-stopped
